# Generated by Django 5.0.1 on 2024-02-14 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='default_profile.png', upload_to='profile_images/', verbose_name='Profile Image')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('mobile_number', models.BigIntegerField(verbose_name='Mobile Number')),
                ('id_proof', models.FileField(upload_to='resumes/', verbose_name='Aadhaar Card')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker',
                'verbose_name_plural': 'Job Seekers',
                'permissions': [('can_view_donors_custom', 'Can View Job Donors Custom')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(upload_to='company_images/', verbose_name='Company Image')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Full Name')),
                ('lic_no', models.CharField(max_length=15, verbose_name='Licence Number')),
                ('lic_doc', models.FileField(upload_to='gst_documents/', verbose_name='Upload Licence Proof')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('mobile_number', models.BigIntegerField(verbose_name='Mobile Number')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_recruiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'permissions': [('can_view_volunteer_custom', 'Can View Volunteer Custom')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_title', models.CharField(max_length=100)),
                ('donation_description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_image', models.ImageField(null=True, upload_to='company_images/', verbose_name='Company Image')),
                ('donation_location', models.CharField(max_length=100)),
                ('donation_type', models.CharField(choices=[('money', 'Money'), ('goods', 'Goods'), ('time', 'Time'), ('food', 'Food'), ('clothing', 'Clothing'), ('books', 'Books'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('medical_supplies', 'Medical Supplies'), ('vehicles', 'Vehicles'), ('appliances', 'Appliances'), ('artwork', 'Artwork'), ('sports_equipment', 'Sports Equipment'), ('tools', 'Tools')], max_length=20)),
                ('contact_information', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recuiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuiter', to='app.donormodel')),
                ('applicants', models.ManyToManyField(blank=True, related_name='applied_jobs', to='app.volunteermodel')),
            ],
        ),
    ]
