# Generated by Django 5.0.1 on 2024-03-25 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donormodel_volunteermodel_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donormodel',
            options={'permissions': [('can_view_donors_custom', 'Can View Job Donors Custom')], 'verbose_name': 'Donor Model', 'verbose_name_plural': 'Donor Model'},
        ),
        migrations.AddField(
            model_name='donation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_donation', to='app.volunteermodel'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recuiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='app.donormodel'),
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_recruiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
